# Infected - A plugin by AnomalousRei
# http://github.com/AnomalousRei/Infected

database:
    type: "MySQL"
    port: 3306
    hostname: "localhost"
    username: "root"
    password: "banana"
    database: "Infected"